# This file was auto-generated by anilibria_api_client/types/scripts/generate_codegen.py.
# DO NOT EDIT MANUALLY.


from __future__ import annotations
from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel
from enum import Enum
from uuid import UUID


class AccountsOtpLogin(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    token: str | None = Field(None, examples=['eyJpdiI6ImJDeElkYzliNFBDb2VFMDdtdnZpdVE9PSIsInZhbHVlIjoiM0Y5SnVINno3NndBbUcvU2NPVjJhMmhTMllJdWd4WUlF=='])


class AccountsOtpOtp(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    code: str | None = Field(None, examples=['058701'])
    device_id: str | None = Field(None, examples=['n702175b-fa52-5251-a39z-d1f4af0w1cak'])
    expired_at: AwareDatetime | None = Field(None, description='Срок действия кода', examples=['2021-09-28T19:40:26+00:00'])
    user_id: int | None = Field(None, examples=[1337])


class AccountsUsersAuthLogin(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    token: str | None = Field(None, examples=['eyJpdiI6IjlhZTBTaU9QZ0pUQ0E5YzZzYzhWRWc9PSIsInZhbHVlIjoiSFZaVHF6Sm45UVBCVk13U1hFYWpRdm1IL0xWWTFpTCtKUUpacDhqSk9LZEY1N0R1MURsN3A5VWRvUFp2OU5YYSIsIm1hYyI6IjUyYTM1NmM5ZGNkNGRiOTFiZmM3Y2FhZmY1ZGQ2MTAzOTc4MDNlMGM2MDg1OWNiMjFlODRiNGIyZGRiNTU1YTIifQ=='])


class AccountsUsersAuthLogout(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    token: None = Field(None, examples=['null'])


class AccountsUsersAuthSocialAuthenticate(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    token: str | None = Field(None, description='JWT токен авторизации', examples=['eyJpdiI6IjlhZTBTaU9QZ0pUQ0E5YzZzYzhWRWc9PSIsInZhbHVlIjoiSFZaVHF6Sm45UVBCVk13U1hFYWpRdm1IL0xWWTFpTCtKUUpacDhqSk9LZEY1N0R1MURsN3A5VWRvUFp2OU5YYSIsIm1hYyI6IjUyYTM1NmM5ZGNkNGRiOTFiZmM3Y2FhZmY1ZGQ2MTAzOTc4MDNlMGM2MDg1OWNiMjFlODRiNGIyZGRiNTU1YTIifQ=='])


class AccountsUsersAuthSocialLogin(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    state: str | None = Field(None, description='Ключ для аутентификации пройденной авторизации', examples=['9xLcqDvd08tTPODsHAXgcidxOvpg3P7Nuc'])
    url: str | None = Field(None, description='Ссылка на oauth авторизацию через указанную социальную сеть', examples=['https://oauth.vk.com/authorize?client_id=&redirect_uri=&scope=email&response_type=code&state=9xLcqDvd08tTPODsHAXgcidxOvpg3P7Nuc'])


class AccountsUsersMeFavoritesIdsItem(RootModel[int]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: int = Field(..., examples=[9023], title='AccountsUsersMeFavoritesIdsItem')


class AccountsUsersMeFavoritesReferencesGenre(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: int | None = Field(None, description='Идентификатор жанра')
    name: str | None = Field(None, description='Название жанра')


class AccountsUsersMeFavoritesReferencesGenres(RootModel[list[AccountsUsersMeFavoritesReferencesGenre]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[AccountsUsersMeFavoritesReferencesGenre] = Field(..., title='AccountsUsersMeFavoritesReferencesGenres')


class AccountsUsersMeFavoritesReferencesYears(RootModel[list[int]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[int] = Field(..., examples=[[2020, 2021, 2022, 2023]], title='AccountsUsersMeFavoritesReferencesYears')


class AccountsUsersMeFavoritesUpdate(RootModel[list[AccountsUsersMeFavoritesIdsItem]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[AccountsUsersMeFavoritesIdsItem] = Field(..., description='Список ID релизов в избранном', examples=[[9023, 9024, 9025]], title='AccountsUsersMeFavoritesUpdate')


class AccountsUsersUserView(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: int | None = Field(None, description='ID записи просмотра', examples=[123])
    is_watched: bool | None = Field(None, description='Флаг, просмотрен ли эпизод полностью', examples=[True])
    release_episode_id: str | None = Field(None, description='ID эпизода релиза', examples=['9b5e26ee-598f-4b8b-b77e-188d3e456318'])
    time: int | None = Field(None, description='Таймкод просмотра, в секундах от начала эпизода', examples=[127.45])
    updated_at: AwareDatetime | None = Field(None, description='Дата обновления записи', examples=['2025-06-23T14:00:00+00:00'])
    user_id: int | None = Field(None, description='ID пользователя', examples=[42])


class AdsBannerPlacement(str, Enum):
    home_support = 'HOME_SUPPORT'
    release_sidebar = 'RELEASE_SIDEBAR'


class AdsStatisticsEventType(str, Enum):
    ad_vast_show = 'AD_VAST_SHOW'
    ad_vast_request = 'AD_VAST_REQUEST'
    ad_banner_view = 'AD_BANNER_VIEW'
    ad_banner_click = 'AD_BANNER_CLICK'
    media_promotion_view = 'MEDIA_PROMOTION_VIEW'
    media_promotion_click = 'MEDIA_PROMOTION_CLICK'


class AdsVastsVast(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ad_company_itn: str | None = Field(None, examples=['1234567890'])
    ad_company_name: str | None = Field(None, examples=['Company XYZ'])
    ad_erid: str | None = Field(None, examples=['ERID123456789'])
    id: str | None = Field(None, examples=['17974e6e-da62-427b-9937-9021cf4cafe4'])
    url: str | None = Field(None, examples=['https://example.com/vast.xml'])


class AgeRating(str, Enum):
    r0_plus = 'R0_PLUS'
    r6_plus = 'R6_PLUS'
    r12_plus = 'R12_PLUS'
    r16_plus = 'R16_PLUS'
    r18_plus = 'R18_PLUS'


class AnimeCatalogReferencesAgeRating(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = Field(None, description='Описание типа', examples=['PG'])
    label: str | None = Field(None, description='Название типа', examples=['PG-17'])
    value: AgeRating | None = None


class AnimeCatalogReferencesAgeRatings(RootModel[list[AnimeCatalogReferencesAgeRating]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[AnimeCatalogReferencesAgeRating] = Field(..., title='AnimeCatalogReferencesAgeRatings')


class AnimeCatalogReferencesGenre(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: int | None = Field(None, description='ID жанра', examples=[23])
    name: str | None = Field(None, description='Название жанра', examples=['Мистика'])


class AnimeCatalogReferencesGenres(RootModel[list[AnimeCatalogReferencesGenre]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[AnimeCatalogReferencesGenre] = Field(..., title='AnimeCatalogReferencesGenres')


class AnimeCatalogReferencesYears(RootModel[list[int]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[int] = Field(..., description='Массив годов', examples=[[2020, 2021, 2022, 2023]], title='AnimeCatalogReferencesYears')


class AnimeEpisodeTimecodeResponse(AccountsUsersUserView):
    pass
    model_config = ConfigDict(
        populate_by_name=True,
    )


class AnimeFranchiseRelease(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    franchise_id: str | None = Field(None, description='Идентификатор франшизы', examples=['3f69ea9b-c202-4522-96b9-07a5de8aa963'])
    id: str | None = Field(None, description='ID связки релиз — франшиза', examples=['db1ebabd-b4b8-4391-85f3-79294515641a'])
    release_id: int | None = Field(None, description='Идентификатор релиза', examples=[9045])
    sort_order: int | None = Field(None, description='Порядок сортировки', examples=[2])


class AnimeReleaseAgeRating(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = Field(None, examples=['Для людей, достигших возраста шестнадцати лет (16+)'])
    is_adult: bool | None = Field(None, examples=[False])
    label: str | None = Field(None, examples=['16+'])
    value: AgeRating | None = None


class AnimeReleaseEpisodeSkip(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    start: float | None = Field(None, description='Время начала. Количество секунд от начала или конца эпизода', examples=[6])
    stop: float | None = Field(None, description='Время окончания. Количество секунд от начала или конца эпизода', examples=[125])


class AnimeReleaseEpisodeTimecodesResponse(RootModel[list[AccountsUsersUserView]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[AccountsUsersUserView] = Field(..., title='AnimeReleaseEpisodeTimecodesResponse')


class AnimeReleaseMemberRole(str, Enum):
    poster = 'poster'
    timing = 'timing'
    voicing = 'voicing'
    editing = 'editing'
    decorating = 'decorating'
    translating = 'translating'


class AnimeReleaseMemberRoleDetails(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = Field(None, examples=['Озвучка'])
    value: AnimeReleaseMemberRole | None = None


class AnimeReleaseName(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    alternative: str | None = Field(None, examples=['Война в Андерворлде, War of Underworld'])
    english: str | None = Field(None, examples=['Sword Art Online: Alicization'])
    main: str | None = Field(None, examples=['Мастера Меча Онлайн: Алисизация'])


class AnimeReleasePublishDay(int, Enum):
    integer_1 = 1
    integer_2 = 2
    integer_3 = 3
    integer_4 = 4
    integer_5 = 5
    integer_6 = 6
    integer_7 = 7


class AnimeReleasePublishDayDetails(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = Field(None, examples=['Воскресенье'])
    value: AnimeReleasePublishDay | None = None


class AnimeSponsorsSponsor(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = Field(None, examples=['Лучший спонсор в мире!'])
    id: str | None = Field(None, description='Transform pattern', examples=['UUID'])
    title: str | None = Field(None, examples=['Sponsor name'])
    url: str | None = Field(None, examples=['https://yandex.ru'])
    url_title: str | None = Field(None, examples=['Переходи по ссылке'])


class Request(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    country: str | None = Field(None, examples=['Russia'])
    ip: str | None = Field(None, examples=['192.168.1.1'])
    iso_code: str | None = Field(None, examples=['RU'])
    timezone: str | None = Field(None, examples=['Europe/Moscow'])


class AppStatus(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    available_api_endpoints: list[str] | None = Field(None, examples=[['https://aniliberty.top']])
    is_alive: bool | None = Field(None, examples=[True])
    request: Request | None = None


class CollectionType(str, Enum):
    planned = 'PLANNED'
    watched = 'WATCHED'
    watching = 'WATCHING'
    postponed = 'POSTPONED'
    abandoned = 'ABANDONED'


class ComponentsImage(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    preview: str | None = Field(None, description='Ссылка на изображение', examples=['/...GoH5bzLFS7A21DzacgUApScj7qJY1iMz.(jpg|webp)'])
    thumbnail: str | None = Field(None, description='Ссылка на изображение', examples=['/.../GoH5bzLFS7A21DzacgUApScj7qJY1iMz.(jpg|webp)'])


class ComponentsImageWithOptimized(ComponentsImage):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    optimized: ComponentsImage | None = None


class ContentType(str, Enum):
    tv = 'TV'
    ona = 'ONA'
    web = 'WEB'
    ova = 'OVA'
    oad = 'OAD'
    movie = 'MOVIE'
    dorama = 'DORAMA'
    special = 'SPECIAL'


class MediaVideosVideoContent(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    comments: int | None = Field(None, description='Количество комментариев под роликом', examples=[532])
    created_at: AwareDatetime | None = Field(None, examples=['2021-09-22T16:20:38+00:00'])
    id: int | None = Field(None, examples=[57])
    image: ComponentsImageWithOptimized | None = None
    is_announce: bool | None = Field(None, description='Видео является анонсом сезона', examples=[True])
    title: str | None = Field(None, examples=['ТОП 10 САМЫХ ОЖИДАЕМЫХ АНИМЕ ОСЕНИ 2021'])
    updated_at: AwareDatetime | None = Field(None, description='Дата последнего обновления данных', examples=['2021-09-28T19:40:26+00:00'])
    url: str | None = Field(None, examples=['https://www.youtube.com/watch?v=8f6FpV4sB0I'])
    video_id: str | None = Field(None, examples=['8f6FpV4sB0I'])
    views: int | None = Field(None, description='Количество просмотров ролика', examples=[34456])


class Model422Content(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    errors: dict[str, list[str]] | None = None


class ProductionStatusesType(str, Enum):
    is_in_production = 'IS_IN_PRODUCTION'
    is_not_in_production = 'IS_NOT_IN_PRODUCTION'


class PublishStatusesType(str, Enum):
    is_ongoing = 'IS_ONGOING'
    is_not_ongoing = 'IS_NOT_ONGOING'


class Seasons(str, Enum):
    winter = 'winter'
    spring = 'spring'
    summer = 'summer'
    autumn = 'autumn'


class SortType(str, Enum):
    fresh_at_desc = 'FRESH_AT_DESC'
    fresh_at_asc = 'FRESH_AT_ASC'
    rating_desc = 'RATING_DESC'
    rating_asc = 'RATING_ASC'
    year_desc = 'YEAR_DESC'
    year_asc = 'YEAR_ASC'


class TeamsTeam(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = Field(None, description='Описание команды')
    id: str | None = Field(None, description='ID команды')
    sort_order: int | None = Field(None, description='Порядок сортировки команды')
    title: str | None = Field(None, description='Название команды')


class TeamsTeamRole(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    color: str | None = Field(None, description='Цвет')
    id: str | None = Field(None, description='ID роли')
    sort_order: int | None = Field(None, description='Порядок сортировки роли')
    title: str | None = Field(None, description='Название роли')


class TeamsTeamUser(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | None = Field(None, description='ID анилибрийца')
    is_intern: bool | None = Field(None, description='Флаг, указывающий, является ли пользователь стажером')
    is_vacation: bool | None = Field(None, description='Флаг, указывающий, находится ли пользователь в отпуске')
    nickname: str | None = Field(None, description='Псевдоним анилибрийца в команде')
    sort_order: int | None = Field(None, description='Порядок сортировки внутри команды')


class TeamsTeamUserAccount(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    avatar: ComponentsImageWithOptimized | None = None
    id: int | None = Field(None, description='ID анилибрийца')
    nickname: str | None = Field(None, description='Псевдоним анилибрийца в команде')


class TeamsUser(TeamsTeamUser):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    team: TeamsTeam | None = None
    user: TeamsTeamUserAccount | None = None
    roles: list[TeamsTeamRole] | None = None


class TeamsUsers(RootModel[list[TeamsUser]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[TeamsUser] = Field(..., title='TeamsUsers')


class TorrentCodec(str, Enum):
    av1 = 'AV1'
    x264_avc = 'x264/AVC'
    x265_hevc = 'x265/HEVC'
    x265hq_hevc_hq = 'x265hq/HEVC-HQ'


class TorrentColor(str, Enum):
    field_8bit = '8bit'
    field_10_bit = '10Bit'


class TorrentMemberRole(str, Enum):
    hevc = 'HEVC'


class TorrentQuality(str, Enum):
    field_360p = '360p'
    field_480p = '480p'
    field_576p = '576p'
    field_720p = '720p'
    field_1080p = '1080p'
    field_2k = '2k'
    field_4k = '4k'
    field_8k = '8k'


class TorrentType(str, Enum):
    bd_rip = 'BDRip'
    hd_rip = 'HDRip'
    tv_rip = 'TVRip'
    web_rip = 'WEBRip'
    dtv_rip = 'DTVRip'
    dvd_rip = 'DVDRip'
    hdtv_rip = 'HDTVRip'
    web_dl = 'WEB-DL'
    web_dl_rip = 'WEB-DLRip'


class UserCollectionAgeRatingsResponse1(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = Field(None, description='Описание типа')
    label: str | None = Field(None, description='Название типа')
    value: AgeRating | None = None


class UserCollectionAgeRatingsResponse(RootModel[list[UserCollectionAgeRatingsResponse1]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[UserCollectionAgeRatingsResponse1] = Field(..., title='UserCollectionAgeRatingsResponse')



UserCollectionGenresResponse1 = AccountsUsersMeFavoritesReferencesGenre




class UserCollectionGenresResponse(RootModel[list[UserCollectionGenresResponse1]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[UserCollectionGenresResponse1] = Field(..., title='UserCollectionGenresResponse')


class UserCollectionIdItem1(RootModel[float]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: float = Field(..., description='Идентификатор релиза', examples=[8345], title='UserCollectionIdItem')


class UserCollectionIdItem(RootModel[UserCollectionIdItem1 | CollectionType]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: UserCollectionIdItem1 | CollectionType = Field(..., title='UserCollectionIdItem')


class UserCollectionIdsResponse(RootModel[list[UserCollectionIdItem]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[UserCollectionIdItem] = Field(..., title='UserCollectionIdsResponse')


class UserCollectionTypesResponse1(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = Field(None, description='Описание типа')
    value: ContentType | None = None


class UserCollectionTypesResponse(RootModel[list[UserCollectionTypesResponse1]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[UserCollectionTypesResponse1] = Field(..., title='UserCollectionTypesResponse')


class UserCollectionYearsResponse(RootModel[list[int]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[int] = Field(..., examples=[[2020, 2021, 2022, 2023]], title='UserCollectionYearsResponse')


class UserCollectionsDeleteResponse(RootModel[list[UserCollectionIdItem]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[UserCollectionIdItem] = Field(..., description='Результат удаления релизов из коллекций', title='UserCollectionsDeleteResponse')


class UserCollectionsUpdateResponse(RootModel[list[UserCollectionIdItem]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[UserCollectionIdItem] = Field(..., description='Результат добавления релизов в коллекции', title='UserCollectionsUpdateResponse')


class UserFavoriteFilterSorting(str, Enum):
    created_at_desc = 'CREATED_AT_DESC'
    created_at_asc = 'CREATED_AT_ASC'
    fresh_at_desc = 'FRESH_AT_DESC'
    fresh_at_asc = 'FRESH_AT_ASC'
    rating_desc = 'RATING_DESC'
    rating_asc = 'RATING_ASC'
    year_desc = 'YEAR_DESC'
    year_asc = 'YEAR_ASC'


class UserSocialType(str, Enum):
    vk = 'vk'
    google = 'google'
    patreon = 'patreon'
    discord = 'discord'


class UserViewTimecode1(RootModel[UUID]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: UUID = Field(..., examples=['68d4d5c5-e3d5-419f-a21c-c511b6b251f5'], title='UserViewTimecode')


class UserViewTimecode2(RootModel[float]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: float = Field(..., examples=[743], title='UserViewTimecode')


class UserViewTimecode3(RootModel[bool]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: bool = Field(..., examples=[True], title='UserViewTimecode')


class UserViewTimecode(RootModel[UserViewTimecode1 | UserViewTimecode2 | UserViewTimecode3]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: UserViewTimecode1 | UserViewTimecode2 | UserViewTimecode3 = Field(..., title='UserViewTimecode')


class UserViewTimecodesResponse(RootModel[list[UserViewTimecode]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[UserViewTimecode] = Field(..., title='UserViewTimecodesResponse')


class Torrents(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    downloaded: int | None = Field(None, description='Количество скачанного, в байтах', examples=[2397162874432])
    passkey: str | None = Field(None, description='passkey, отображается только собственный', examples=['xBSmRDA95bJXPk3E'])
    uploaded: int | None = Field(None, description='Количество отданного, в байтах', examples=[998234623])


class UsersUser(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    avatar: ComponentsImageWithOptimized | None = None
    created_at: AwareDatetime | None = Field(None, examples=['2019-03-31T20:43:52+00:00'])
    email: str | None = Field(None, description='Отображается только собственный', examples=['animeshnik_488@protonmail.com'])
    id: int | None = Field(None, description='Transform pattern', examples=[4837362])
    is_banned: bool | None = Field(None, description='Забанен ли пользоваель в данный момент', examples=[True])
    is_with_ads: bool | None = Field(None, description='Отображение рекламы', examples=[False])
    login: str | None = Field(None, description='Отображается только собственный', examples=['animeshnik_488'])
    nickname: str | None = Field(None, examples=['Animeshnik488'])
    torrents: Torrents | None = Field(None, description='Данные по торрентам')


class Browser(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str | None = Field(None, examples=['Chrome'])
    version: str | None = Field(None, examples=['112.0'])


class Device(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: str | None = Field(None, examples=['Macintosh'])
    platform: str | None = Field(None, examples=['Mac OS X'])
    version: str | None = Field(None, examples=['10.15'])


class Location(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    country: str | None = Field(None, examples=['Russia'])
    iso_code: str | None = Field(None, examples=['RU'])


class UsersUserSession(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    browser: Browser | None = Field(None, description='Информация о браузере')
    device: Device | None = Field(None, description='Информация об устройстве')
    id: str | None = Field(None, description='Transform pattern', examples=['XbSmRDA95bJXPk3E'])
    ip_address: str | None = Field(None, description='IP-адрес', examples=['192.168.1.1'])
    is_current: bool | None = Field(None, description='Текущая сессия', examples=[True])
    is_desktop: bool | None = Field(None, description='Десктопное устройство', examples=[True])
    is_mobile: bool | None = Field(None, description='Мобильное устройство', examples=[False])
    last_active: AwareDatetime | None = Field(None, examples=['2024-03-01T12:34:56+00:00'])
    location: Location | None = Field(None, description='Геолокация пользователя')
    user_agent: str | None = Field(None, description='User-Agent', examples=['Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)'])
    user_id: int | None = Field(None, examples=[482903])


class Links(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    next: str | None = Field(None, examples=['/api/version/path-to-resource?page=3'])
    previous: str | None = Field(None, examples=['/api/version/path-to-resource?page=1'])


class Pagination(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    count: int | None = Field(None, examples=['10'])
    current_page: int | None = Field(None, examples=['5'])
    links: Links | None = None
    per_page: int | None = Field(None, examples=['10'])
    total: int | None = Field(None, examples=['1704'])
    total_pages: int | None = Field(None, examples=['171'])


class UtilsPaginationSchemesMeta(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    pagination: Pagination | None = None


class VideoOriginType(str, Enum):
    youtube_playlist = 'YOUTUBE_PLAYLIST'


class AccountsOtpGet(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    otp: AccountsOtpOtp | None = None
    remaining_time: int | None = Field(None, examples=[120])


class AccountsUsersMeFavoritesDelete(RootModel[list[AccountsUsersMeFavoritesIdsItem]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[AccountsUsersMeFavoritesIdsItem] = Field(..., description='Список ID релизов, оставшихся в избранном после удаления', examples=[[9021, 9022]], title='AccountsUsersMeFavoritesDelete')


class AccountsUsersMeFavoritesIds(RootModel[list[AccountsUsersMeFavoritesIdsItem]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[AccountsUsersMeFavoritesIdsItem] = Field(..., description='Список ID релизов в избранном', examples=[[9023, 9024, 9025]], title='AccountsUsersMeFavoritesIds')


class AccountsUsersMeFavoritesReferencesAgeRating(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = Field(None, description='Описание рейтинга')
    label: str | None = Field(None, description='Название рейтинга')
    value: AgeRating | None = None


class AccountsUsersMeFavoritesReferencesAgeRatings(RootModel[list[AccountsUsersMeFavoritesReferencesAgeRating]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[AccountsUsersMeFavoritesReferencesAgeRating] = Field(..., title='AccountsUsersMeFavoritesReferencesAgeRatings')


class AccountsUsersMeFavoritesReferencesSorting1(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = Field(None, description='Описание опции сортировки')
    label: str | None = Field(None, description='Название опции сортировки')
    value: UserFavoriteFilterSorting | None = None


class AccountsUsersMeFavoritesReferencesSorting(RootModel[list[AccountsUsersMeFavoritesReferencesSorting1]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[AccountsUsersMeFavoritesReferencesSorting1] = Field(..., title='AccountsUsersMeFavoritesReferencesSorting')


class AccountsUsersMeFavoritesReferencesType(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = Field(None, description='Описание типа релиза')
    value: ContentType | None = None


class AccountsUsersMeFavoritesReferencesTypes(RootModel[list[AccountsUsersMeFavoritesReferencesType]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[AccountsUsersMeFavoritesReferencesType] = Field(..., title='AccountsUsersMeFavoritesReferencesTypes')


class AdsBannersBanner(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ad_company_itn: str | None = Field(None, examples=['7707083893'])
    ad_company_name: str | None = Field(None, examples=['ООО "Аниме Медиа Групп"'])
    ad_erid: str | None = Field(None, examples=['CZkqkNu5u8N'])
    button_title: str | None = Field(None, examples=['Подписаться'])
    button_url: str | None = Field(None, examples=['https://aniliberty.top/subscribe'])
    description: str | None = Field(None, examples=['Смотри любимые сериалы без ограничений'])
    has_overlay: bool | None = Field(None, examples=[True])
    id: int | None = Field(None, examples=[101])
    image: ComponentsImageWithOptimized | None = None
    image_url: str | None = Field(None, examples=['https://external.site/banner.jpg'])
    placement: AdsBannerPlacement | None = None
    title: str | None = Field(None, examples=['Смотри аниме без рекламы!'])


class AdsVasts(RootModel[list[AdsVastsVast]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[AdsVastsVast] = Field(..., title='AdsVasts')


class AnimeCatalogReferencesProductionStatus(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = Field(None, description='Описание статуса', examples=['Сейчас в озвучке'])
    value: ProductionStatusesType | None = None


class AnimeCatalogReferencesProductionStatuses(RootModel[list[AnimeCatalogReferencesProductionStatus]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[AnimeCatalogReferencesProductionStatus] = Field(..., title='AnimeCatalogReferencesProductionStatuses')


class AnimeCatalogReferencesPublishStatus(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = Field(None, description='Описание статуса', examples=['Онгоинг'])
    value: PublishStatusesType | None = None


class AnimeCatalogReferencesPublishStatuses(RootModel[list[AnimeCatalogReferencesPublishStatus]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[AnimeCatalogReferencesPublishStatus] = Field(..., title='AnimeCatalogReferencesPublishStatuses')


class AnimeCatalogReferencesSeason(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = Field(None, description='Название сезона', examples=['Зима'])
    value: Seasons | None = None


class AnimeCatalogReferencesSeasons(RootModel[list[AnimeCatalogReferencesSeason]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[AnimeCatalogReferencesSeason] = Field(..., title='AnimeCatalogReferencesSeasons')


class AnimeCatalogReferencesSorting1(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = Field(None, description='Описание типа', examples=['Сначала отобразятся самые непопулярные релизы'])
    label: str | None = Field(None, description='Название типа', examples=['Самый низкий рейтинг'])
    value: SortType | None = None


class AnimeCatalogReferencesSorting(RootModel[list[AnimeCatalogReferencesSorting1]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[AnimeCatalogReferencesSorting1] = Field(..., title='AnimeCatalogReferencesSorting')


class AnimeCatalogReferencesType(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = Field(None, description='Название типа', examples=['ТВ'])
    value: ContentType | None = None


class AnimeCatalogReferencesTypes(RootModel[list[AnimeCatalogReferencesType]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[AnimeCatalogReferencesType] = Field(..., title='AnimeCatalogReferencesTypes')


class AnimeFranchisesFranchise(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    first_year: int | None = Field(None, description='Год первого релиза', examples=[2010])
    id: str | None = Field(None, description='Идентификатор франшизы', examples=['116e17d2-e89f-4ffc-bfa4-b45ae4c41e92'])
    image: ComponentsImageWithOptimized | None = None
    last_year: int | None = Field(None, description='Год последнего релиза', examples=[2023])
    name: str | None = Field(None, description='Название франшизы (на русском)', examples=['Re: Жизнь в другом мире с нуля'])
    name_english: str | None = Field(None, description='Название франшизы (на английском)', examples=['Re: Zero kara Hajimeru Isekai Seikatsu'])
    rating: float | None = Field(None, description='Рейтинг франшизы', examples=[8.45])
    total_duration: str | None = Field(None, description='Общая длительность франшизы', examples=['2 дня 5 часов'])
    total_duration_in_seconds: int | None = Field(None, description='Общая длительность франшизы в секундах', examples=[183600])
    total_episodes: int | None = Field(None, description='Общее количество эпизодов', examples=[25])
    total_releases: int | None = Field(None, description='Количество релизов', examples=[10])


class AnimeFranchisesRandom(RootModel[list[AnimeFranchisesFranchise]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[AnimeFranchisesFranchise] = Field(..., title='AnimeFranchisesRandom')


class AnimeGenresGenre(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: int | None = Field(None, examples=[21])
    image: ComponentsImageWithOptimized | None = None
    name: str | None = Field(None, examples=['Комедия'])
    total_releases: int | None = Field(None, description='Общее количество релизов в этом жанре', examples=[10])


class AnimeGenresItem(AnimeGenresGenre):
    pass
    model_config = ConfigDict(
        populate_by_name=True,
    )


class AnimeGenresList(RootModel[list[AnimeGenresGenre]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[AnimeGenresGenre] = Field(..., title='AnimeGenresList')


class AnimeReleaseEpisode(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    duration: float | None = Field(None, description='Длительность эпизода в секундах', examples=[1432])
    ending: AnimeReleaseEpisodeSkip | None = None
    hls_1080: str | None = Field(None, description='Ссылка на поток 1080p')
    hls_480: str | None = Field(None, description='Ссылка на поток 480p')
    hls_720: str | None = Field(None, description='Ссылка на поток 720p')
    id: str | None = Field(None, description='Идентификатор эпизода', examples=['9b5e26ee-598f-4b8b-b77e-188d3e456318'])
    name: str | None = Field(None, description='Название эпизода', examples=['Пролог'])
    name_english: str | None = Field(None, description='Название эпизода на английском', examples=['Prologue'])
    opening: AnimeReleaseEpisodeSkip | None = None
    ordinal: float | None = Field(None, description='Номер эпизода. Может быть целым или дробным числом (например, 5 или 23.5)', examples=[12.5])
    preview: ComponentsImageWithOptimized | None = None
    release_id: float | None = Field(None, description='Идентификатор релиза', examples=[9324])
    rutube_id: str | None = Field(None, description='Id эпизода на Rutube', examples=['c6cc4d620b1d4338901770a44b3e82f4'])
    sort_order: float | None = Field(None, description='Порядковый номер эпизода для сортировки', examples=[12])
    updated_at: AwareDatetime | None = Field(None, description='Дата обновления эпизода', examples=['2021-11-25T18:46:30+00:00'])
    youtube_id: str | None = Field(None, description='Id эпизода на Youtube', examples=['dQw4w9WgXcQ'])


class AnimeReleaseMemberUser(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    avatar: ComponentsImageWithOptimized | None = None
    id: float | None = Field(None, examples=[2346])


class AnimeReleaseSeasonDetails(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = Field(None, examples=['Осень'])
    value: Seasons | None = None


class AnimeReleaseTypeDetails(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = Field(None, examples=['ТВ'])
    value: ContentType | None = None


class AnimeTorrentsTorrentCodec(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = Field(None, examples=['x264/AVC'])
    label: str | None = Field(None, examples=['AVC'])
    label_color: str | None = Field(None, description='Цвет лейбла', examples=['#FFF'])
    label_is_visible: bool | None = Field(None, description='Отображать ли лейбл рядом с торрентом', examples=[True])
    value: TorrentCodec | None = None


class AnimeTorrentsTorrentColor(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = Field(None, examples=['8-bit'])
    value: TorrentColor | None = None


class AnimeTorrentsTorrentMemberRole(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = Field(None, examples=['HEVC'])
    value: TorrentMemberRole | None = None



AnimeTorrentsTorrentMemberUser = AnimeReleaseMemberUser




class AnimeTorrentsTorrentQuality(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = Field(None, examples=['1080p'])
    value: TorrentQuality | None = None


class AnimeTorrentsTorrentType(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = Field(None, examples=['WEBRip'])
    value: TorrentType | None = None


class MediaVideosVideoOriginType(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = Field(None, examples=['YouTube плейлист'])
    value: VideoOriginType | None = None


class Teams(RootModel[list[TeamsTeam]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[TeamsTeam] = Field(..., title='Teams')


class TeamsRoles(RootModel[list[TeamsTeamRole]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[TeamsTeamRole] = Field(..., title='TeamsRoles')


class AnimeFranchises(RootModel[list[AnimeFranchisesFranchise]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[AnimeFranchisesFranchise] = Field(..., title='AnimeFranchises')


class AnimeGenres(RootModel[list[AnimeGenresGenre]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[AnimeGenresGenre] = Field(..., title='AnimeGenres')


class AnimeRelease(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    added_in_abandoned_collection: float | None = Field(None, description='Кол-во добавлений в ABANDONED коллекцию', examples=[12])
    added_in_planned_collection: float | None = Field(None, description='Кол-во добавлений в PLANNED коллекцию', examples=[2457])
    added_in_postponed_collection: float | None = Field(None, description='Кол-во добавлений в POSTPONED коллекцию', examples=[212])
    added_in_users_favorites: float | None = Field(None, description='Рейтинг по добавлению в коллекцию', examples=[25557])
    added_in_watched_collection: float | None = Field(None, description='Кол-во добавлений в WATCHED коллекцию', examples=[467])
    added_in_watching_collection: float | None = Field(None, description='Кол-во добавлений в WATCHING коллекцию', examples=[346])
    age_rating: AnimeReleaseAgeRating | None = None
    alias: str | None = Field(None, description='Ссылка на релиз', examples=['sword-art-online-alicization'])
    average_duration_of_episode: float | None = Field(None, description='Средняя продолжительность серий', examples=[25])
    created_at: AwareDatetime | None = Field(None, description='Дата создания релиза', examples=['2019-12-29T23:06:39+00:00'])
    description: str | None = Field(None, description='Описание релиза', examples=['Underworld - мир, ранее недоступный человеческому пониманию...'])
    episodes_total: float | None = Field(None, description='Всего эпизодов', examples=[36])
    external_player: str | None = Field(None, description='Ссылка на внешний плеер', examples=['//kodik.info/serial/...'])
    fresh_at: AwareDatetime | None = Field(None, description='Дата поднятия релиза', examples=['2019-12-29T23:06:39+00:00'])
    id: float | None = Field(None, description='Идентификатор релиза', examples=[7439])
    is_blocked_by_copyrights: bool | None = Field(None, description='Релиз заблокирован правообладателем', examples=[False])
    is_blocked_by_geo: bool | None = Field(None, description='Блокировка по геолокации', examples=[False])
    is_in_production: bool | None = Field(None, description='Релиз в работе / озвучивается', examples=[False])
    is_ongoing: bool | None = Field(None, description='Релиз в данный момент выходит в стране производства', examples=[False])
    name: AnimeReleaseName | None = None
    notification: str | None = Field(None, description='Важная информация / Оповещение', examples=['Серии выходят по воскресеньям'])
    poster: ComponentsImageWithOptimized | None = None
    publish_day: AnimeReleasePublishDayDetails | None = None
    season: AnimeReleaseSeasonDetails | None = None
    type: AnimeReleaseTypeDetails | None = None
    updated_at: AwareDatetime | None = Field(None, description='Дата обновления релиза', examples=['2023-08-20T15:08:20+00:00'])
    year: float | None = Field(None, description='Год', examples=[2018])


class AnimeReleaseInSchedule(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    full_season_is_released: bool | None = Field(None, examples=[True])
    next_release_episode_number: int | None = Field(None, examples=[8])
    published_release_episode: AnimeReleaseEpisode | None = None
    release: AnimeRelease | None = None


class AnimeReleaseMember(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | None = Field(None, examples=['uuid...'])
    nickname: str | None = Field(None, examples=['Zvukar'])
    role: AnimeReleaseMemberRoleDetails | None = None
    user: AnimeReleaseMemberUser | None = Field(None, description='Связанный с участником релиза пользователь')


class AnimeReleaseMembersResponse(RootModel[list[AnimeReleaseMember]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[AnimeReleaseMember] = Field(..., title='AnimeReleaseMembersResponse')


class AnimeScheduleNow(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    today: list[AnimeReleaseInSchedule] | None = None
    tomorrow: list[AnimeReleaseInSchedule] | None = None
    yesterday: list[AnimeReleaseInSchedule] | None = None


class AnimeScheduleWeek(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: list[AnimeReleaseInSchedule] | None = None


class AnimeTorrentsTorrent(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    bitrate: int | None = Field(None, description='Битрейт, Кбит/сек', examples=[3400])
    codec: AnimeTorrentsTorrentCodec | None = None
    color: AnimeTorrentsTorrentColor | None = None
    completed_times: int | None = Field(None, description='Общее количество скачиваний торрента', examples=[13538])
    created_at: AwareDatetime | None = Field(None, examples=['2021-09-21T11:45:00+00:00'])
    description: str | None = Field(None, description='Описание торрента', examples=['1-17 + OVA(1-4)'])
    filename: str | None = Field(None, examples=['Shaman King (2021) - AniLiberty.TOP [WEB-Rip 1080p].torrent'])
    hash: str | None = Field(None, examples=['8a8fb94b1bd22b44a116336bab6bf209d0ac3a90'])
    id: int | None = Field(None, examples=[18523])
    is_hardsub: bool | None = Field(None, description='Является ли торрент хардсабом', examples=[True])
    label: str | None = Field(None, examples=['Shaman King (2021) - AniLiberty.TOP [WEB-Rip 1080p]'])
    leechers: int | None = Field(None, description='Количество личеров', examples=[58])
    magnet: str | None = Field(None, examples=['magnet:?xt=urn:btih:QPYNLG5Y2LA2KHB7SZCQF2W3...'])
    quality: AnimeTorrentsTorrentQuality | None = None
    seeders: int | None = Field(None, description='Количество сидеров', examples=[234])
    size: int | None = Field(None, description='Размер торрент-файла в байтах', examples=[7356495551])
    sort_order: int | None = Field(None, description='Порядок сортировки торрента внутри релиза', examples=[2])
    type: AnimeTorrentsTorrentType | None = None
    updated_at: AwareDatetime | None = Field(None, examples=['2021-09-22T16:20:38+00:00'])


class AnimeTorrentsTorrentMember(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    external_url: str | None = Field(None, examples=['https://t.me/Animeshnik488'])
    id: str | None = Field(None, examples=['6240acf7-4f62-4de9-9cc0-b3984ccc2b35'])
    nickname: str | None = Field(None, examples=['Tuxoid'])
    role: AnimeTorrentsTorrentMemberRole | None = None


class AppSearchReleasesResponse(RootModel[list[AnimeRelease]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[AnimeRelease] = Field(..., title='AppSearchReleasesResponse')


class MediaPromotionsPromotion(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    ad_erid: str | None = None
    ad_origin: str | None = None
    description: str | None = Field(None, description='Кастомное описание промо-материала', examples=['ИСПЫТАЙ СВОЮ ПАМЯТЬ! Собери все пары карточек правильно, и получи дракона на старте!'])
    has_overlay: bool | None = Field(None, description='Использовать темный оверлей', examples=[True])
    id: str | None = Field(None, examples=['bad864a4-d1b9-473f-898f-da8ee800ef87'])
    image: ComponentsImageWithOptimized | None = None
    is_ad: bool | None = Field(None, description='Флаг рекламной промо кампании', examples=[True])
    release: AnimeRelease | None = None
    title: str | None = Field(None, description='Кастомное название промо-материала', examples=['Dragon Contract'])
    url: str | None = Field(None, description='Кастомная ссылка на промо-материал', examples=['https://espritgames.ru/dragoncontract/promotions/getdragon'])
    url_label: str | None = Field(None, description='Кастомная подпись к ссылке', examples=['Перейти на сайт'])


class MediaVideosVideoOrigin(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = Field(None, examples=['Плейлист с анонсами'])
    id: str | None = Field(None, examples=['e8fd32be-7f14-4c02-bf00-dbd26ecabfdb'])
    is_announce: bool | None = Field(None, description='Видео-источник является анонсом сезона', examples=[True])
    title: str | None = Field(None, examples=['Анонсы аниме-сезонов'])
    type: MediaVideosVideoOriginType | None = None
    url: str | None = Field(None, examples=['https://www.youtube.com/playlist?list=PL8_g6JPJBRglxkyQfNGugDyyQP11hL0-Q'])


class Datum5(AnimeRelease):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    genres: list[AnimeGenresGenre] | None = None
    episodes: list[AnimeReleaseEpisode] | None = None


class UserCollectionReleasesResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: list[Datum5] | None = None
    meta: UtilsPaginationSchemesMeta | None = None



UserFavoriteReleasesResponse = UserCollectionReleasesResponse




class ReleaseEpisode(AnimeReleaseEpisode):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    release: AnimeRelease | None = None


class Datum(AccountsUsersUserView):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    release_episode: ReleaseEpisode | None = None


class AccountsUsersMeViewsHistory(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: list[Datum] | None = None
    meta: UtilsPaginationSchemesMeta | None = None


class Datum1(AnimeRelease):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    genres: list[AnimeGenresGenre] | None = None


class AnimeCatalogReleasesResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: list[Datum1] | None = None
    meta: UtilsPaginationSchemesMeta | None = None


class Release(AnimeRelease):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    episodes: list[AnimeReleaseEpisode] | None = None


class AnimeEpisodeResponse(AnimeReleaseEpisode):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    release: Release | None = None


class FranchiseRelease(AnimeFranchiseRelease):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    release: AnimeRelease | None = None


class AnimeFranchise(AnimeFranchisesFranchise):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    franchise_releases: list[FranchiseRelease] | None = None



AnimeFranchisesByReleaseResponse1 = AnimeFranchise




class AnimeFranchisesByReleaseResponse(RootModel[list[AnimeFranchisesByReleaseResponse1]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[AnimeFranchisesByReleaseResponse1] = Field(..., title='AnimeFranchisesByReleaseResponse')


class AnimeGenreReleasesResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: list[AnimeRelease] | None = None
    meta: UtilsPaginationSchemesMeta | None = None


class AnimeLatestReleasesResponse1(AnimeRelease):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    genres: list[AnimeGenresGenre] | None = None
    latest_episode: AnimeReleaseEpisode | None = None


class AnimeLatestReleasesResponse(RootModel[list[AnimeLatestReleasesResponse1]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[AnimeLatestReleasesResponse1] = Field(..., title='AnimeLatestReleasesResponse')


class AnimeRandomReleasesResponse(RootModel[list[AnimeRelease]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[AnimeRelease] = Field(..., title='AnimeRandomReleasesResponse')


class AnimeRecommendedReleasesResponse(RootModel[list[AnimeRelease]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[AnimeRelease] = Field(..., title='AnimeRecommendedReleasesResponse')


class Datum2(AnimeRelease):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    genres: list[AnimeGenresGenre] | None = None
    members: list[AnimeReleaseMember] | None = None
    episodes: list[AnimeReleaseEpisode] | None = None
    torrents: list[AnimeTorrentsTorrent] | None = None
    sponsors: list[AnimeSponsorsSponsor] | None = None


class AnimeReleaseListResponse(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: list[Datum2] | None = None
    meta: UtilsPaginationSchemesMeta | None = None


class AnimeReleaseResponse(AnimeRelease):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    episodes: list[AnimeReleaseEpisode] | None = None
    genres: list[AnimeGenresGenre] | None = None
    members: list[AnimeReleaseMember] | None = None
    sponsors: list[AnimeSponsorsSponsor] | None = None
    torrents: list[AnimeTorrentsTorrent] | None = None


class TorrentMember(AnimeTorrentsTorrentMember):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    user: AnimeTorrentsTorrentMemberUser | None = None


class AnimeReleaseTorrentsResponse1(AnimeTorrentsTorrent):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    torrent_members: list[TorrentMember] | None = None
    release: AnimeRelease | None = None


class AnimeReleaseTorrentsResponse(RootModel[list[AnimeReleaseTorrentsResponse1]]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: list[AnimeReleaseTorrentsResponse1] = Field(..., title='AnimeReleaseTorrentsResponse')



AnimeTorrent = AnimeReleaseTorrentsResponse1





Datum3 = AnimeReleaseTorrentsResponse1




class AnimeTorrents(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: list[Datum3] | None = None
    meta: UtilsPaginationSchemesMeta | None = None


class MediaPromotions(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: list[MediaPromotionsPromotion] | None = None


class Datum4(MediaVideosVideoContent):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    origin: MediaVideosVideoOrigin | None = None


class MediaVideos(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: list[Datum4] | None = None
