version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
    # You can also specify other tool versions:
    # nodejs: "19"
    # rust: "1.64"
    # golang: "1.19"

  jobs:
    pre_create_environment:
      - asdf global python 3.13
    pre_install:
      - pip install --upgrade pip setuptools wheel

sphinx:
  configuration: docs/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
#    - pdf

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - dependencies
